---
output:
  md_document:
    variant: markdown_github
  html_document:
    variant: markdown_github
    keep_md: true
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
library(knitr)
opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  fig.align = "center",
  fig.retina = 2,
  out.width = "75%",
  dpi = 96
)
knit_hooks$set(pngquant = hook_pngquant)
```

# Data repository pob
This is a data supporting package for the [Portfolio Optimization Book](https://portfoliooptimizationbook.com), with the [developer GitHub webpage](https://github.com/portfoliooptimizationbook).

For additional material, such as slides, exercises, and code examples (R and Python), please check https://portfoliooptimizationbook.com

To install in R:
```{r, eval=FALSE}
devtools::install_github("dppalomar/pob")
```

To install in Python:
```{r, eval=FALSE}
# TBD
```



### Data
The package contains stock data and cryptocurrency data:
```{r}
library(pob)

# stock S&P500 market data
data(SP500_2015to2020)
names(SP500_2015to2020)
head(SP500_2015to2020$stocks[, 1:5])

# crypto data
data(cryptos_2017to2021)
names(cryptos_2017to2021)
head(cryptos_2017to2021$hourly[, 1:5])
```



<!---
### Slides
TBD




### Exercises

- Chapter 9 - High Order Portfolios: [exercises](exercises/ch09-exercises.pdf)

- Chapter 11 - Risk Parity Portfolios: [exercises](exercises/ch11-exercises.pdf)
    
- Appendix A - Convex Optimization Theory: [exercises](exercises/appA-exercises.pdf)

- Appendix B - Optimization Algorithms: [exercices](exercises/appB-exercises.pdf)




### Code examples

- Chapter 6 - Portfolio Basics: [R code](https://raw.githack.com/dppalomar/pob/master/code_examples/R/ch6-R.html), Python code TBD
  
- Chapter 7 - Modern Portfolio Theory: [R code](https://raw.githack.com/dppalomar/pob/master/code_examples/R/ch7-R.html), Python code TBD

--->
