[build-system]
requires = ["setuptools>=40.6.0,<60.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79

[tool.isort]
skip_glob = []
line_length = 79
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true

[tool.coverage.run]
parallel = true
branch = true
source = ["pob"]

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.report]
show_missing = true

[tool.pycln]
all = true

[tool.towncrier]
name = "pob"
package = "pob"
package_dir = "src"
filename = "docs/news.rst"
directory = "news/"
issue_format = "`#{issue} <https://github.com/dppalomar/pob/issues/{issue}>`_"
underlines = "-~~"
